### ISSUE TITLE
Comments from last round of testing

### ISSUE THREAD

**Issue by ZodiusInfuser** [MagicSmokeIndustries/IR-Sequencer#10]
1) I think if you add a command to a running sequence it should cancel the running sequence. It doesn't seem to really break anything but it seems odd, especially if you add a move after a set of already executing moves.
2) Same as above but for deleting commands. Moving commands around already stops the sequence
3) When you pause a sequence there is no indication of this. Suggest changing the usual lime green lights to yellow
4) Pause looks like it jumps back in the sequence (based on the behaviour of the indicators). Should really stay as it was when paused with pint (3) applied.
5) Could consider combining play and pause buttons like music players do
6) In Editor change naming of buttons to [Play] [Pause] [Stop]
7) If you pause on a Delay the displayed value jumps to -1500 (or so) and continues counting down. When resumed the Delay starts from its original value rather than the value it was left at
( 3 ).
8) Some odd behaviour seems to occur if you have one sequence that is paused and another controls the servos. This is in relation to the editor, with it pressing play on the sequence not being edited affects the indicators of the one that is
9) Is the looping button still necessary with the Goto feature?
10) Deleting a sequence should stop it's execution

**Comment by ZodiusInfuser** [comment]
11) Pressing Start on an already running sequence when on a Delay command causes its timer to reset.
12) Re-label editor buttons to Play Pause Stop and update tooltips on those buttons and ones on the Servo Sequencer UI

**Comment by ZiwKerman** [comment]
11 is intended because Start is a Re-Start also

**Comment by ZiwKerman** [comment]
Can be fixed by making Start/Pause a toggle

**Comment by ZodiusInfuser** [comment]
1) and 2) fixed
3) Playhead addresses this, but indicator should also be yellow
4) Explained and made more obvious by playhead
7) Fixed
10) Sequencer stops executing sequence, but Editor window remains if it was previously open.

**Comment by ZodiusInfuser** [comment]
5) fixed
6) & 12) fixed (tooltips seem to be non-functional though so I can't test to confirm if they were updated)
8) seems to be fixed now
9) is being kept and I'll do an icon for it
11) Not applicable anymore

I think this can be closed now

**Comment by ZiwKerman** [comment]
Most of it is fixed. We'll add a separate issues if something is still left on the table.
