### ISSUE TITLE
Suggestion:  Add Sequencer to all pods, not just probe cores.  

### ISSUE THREAD

**Issue by KAmaia** [MagicSmokeIndustries/IR-Sequencer#34]
This is done easily by replacing the data in your MM_IRSequencer_Storage.cfg with

"//Add Sequencer to Cockpits
@PART[*]:HAS[#category[Pods]]
{
    %MODULE[SequencerStorage]{
    }
}
"

This will add it to all command pods.  (Including MODS)

**Comment by ZiwKerman** [comment]
Actually I'm more inclined to have a separate part for sequencer, but I'm
bad at modelling.

You can add sequencer to any part by modifying the MM config supplied.

On Saturday, 19 December 2015, KAmaia notifications@github.com wrote:

> —
> Reply to this email directly or view it on GitHub
> https://github.com/MagicSmokeIndustries/IR-Sequencer/issues/34.

## 

Best regards,
Stepan Andreev

**Comment by KAmaia** [comment]
Stephen, 

I already modified the appropriate file, though I thought it might be useful for others to have that option.

Regards,
Krystal Amaia

Closed::Reason has been addressed reasonably.
