### ISSUE TITLE
CKAN update

### ISSUE THREAD

**Issue by blackk100** [MagicSmokeIndustries/IR-Sequencer#58]
I see that the mod has been recompiled for KSP v1.3, but the release is marked as "Pre-Release". CKAN lists the old version of the mod (v.1.0.0, which is for KSP v1.1.3). Not sure if this is a CKAN issue, but as far as I understand, the release needs to be marked as "Latest Release", otherwise CKAN won't update its modlist.

**Comment by chevyboys** [comment]
Pretty please fix this. The ckan version appears to not have any parts...

**Comment by blackk100** [comment]
Well, this is dead...
